#! /usr/bin/env python3
# $Id$ $Date: Fri Sep 1 10:06:44 2017 -0500$
import shlex, sys
from subprocess import check_output
def main(argv):
    param = ''
    if(len(argv)):
        argc = len(argv)
        param = ' -- ' + argv[0]
    data = sys.stdin.read()
    args = shlex.split('git log --pretty=format:"%ad" -1 ' + param)
    last_date = check_output(args).decode()
    print(data.replace('$Date$', '$Date: ' + last_date + '$'), end='')
if __name__ == "__main__":
    main(sys.argv[1:])

