                                                                                                                                                                                                                                                                                                                    
#include <unistd.h>                                                                                                                                                                                                                                                                                                 
#include <iostream>                                                                                                                                                                                                                                                                                                 
#include <vector>                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                    
using namespace std;                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                    
int main(int argc, char * argv[])                                                                                                                                                                                                                                                                                   
{                                                                                                                                                                                                                                                                                                                   
    /*                                                                                                                                                                                                                                                                                                              
    char space = ' ';                                                                                                                                                                                                                                                                                               
    for (int i = 0; i < argc ; ++i)                                                                                                                                                                                                                                                                                 
    {                                                                                                                                                                                                                                                                                                               
        cerr << argv [i];                                                                                                                                                                                                                                                                                           
        if (argc -1 > i) { cerr << space;}                                                                                                                                                                                                                                                                          
    }                                                                                                                                                                                                                                                                                                               
    //cerr << "'\n";                                                                                                                                                                                                                                                                                                
    */                                                                                                                                                                                                                                                                                                              
    vector<char *> execv_params;                                                                                                                                                                                                                                                                                    
    execv_params.reserve(argc);                                                                                                                                                                                                                                                                                     
    for (int i = 1 ; i < argc ; ++i)                                                                                                                                                                                                                                                                                
    {                                                                                                                                                                                                                                                                                                               
        execv_params.push_back(argv[i]);                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                               
    execv_params.push_back(NULL);
    // cerr << "used len = " << execv_params.size() << "\n";
    char **command = execv_params.data();
    int err = execv(command[0], &command[0]);
    // cerr << "err = " << err << "; errno = " << errno << "\n";
    if (-1 == err)
        exit(errno);
    else exit(EXIT_SUCCESS);
}
