#!/bin/bash

#ident $Id$ $Date$

goline="git you don't exist go away"
echo "$goline"
while read line
do
    test "$LOGNAME" = "$line" && break
    echo "$goline"
done
#done < "${1:-/dev/stdin}"

cmd="
gio mount sftp://ndarmoni@xdev64.xcastlabs.com;

#gvfs-mount 'sftp://ndarmoni@pbxdev.xcastlabs.com';
gio mount sftp://ndarmoni@pbxdev.xcastlabs.com;
#gvfs-mount 'sftp://ndarmoni@pps.siptalk.com';
#gio mount sftp://ndarmoni@pps.siptalk.com;
mount_dev;
mount_pbxdev;
mount_usr
test \$(pgrep -f /usr/bin/pidgin) || /usr/bin/pidgin -f & 2> /dev/null
"
echo "     $cmd"
#for line in $(echo $cmd | tr ";" "\n"); eval "'$line'"; done
eval "$cmd"
