#!/bin/bash

#ident $Id$ $Date$

goline="git you don't exist go away"
until [ "$LOGNAME" = "$line"  ] ; do
    echo "$goline"
    read line
done

cmd="
gio mount sftp://ndarmoni@xdev64.xcastlabs.com;

#gvfs-mount 'sftp://ndarmoni@pbxdev.xcastlabs.com';
gio mount sftp://ndarmoni@pbxdev.xcastlabs.com;
#gvfs-mount 'sftp://ndarmoni@pps.siptalk.com';
#gio mount sftp://ndarmoni@pps.siptalk.com;
#mount_dev;
#mount_pbxdev;
#mount_usr;
test \$(pgrep -f /usr/bin/pidgin) || /usr/bin/pidgin -f & 2> /dev/null
sudo systemctl start rpm_django
#sudo systemctl start middle_collector rpm_django
"
echo "     $cmd"
#for line in $(echo $cmd | tr ";" "\n"); eval "'$line'"; done
eval "$cmd"
