#!/bin/bash

#ident $Id$ $Date$

goline="git you don't exist go away"
echo "$goline"
while read line
do
    echo "$goline"
    test "$LOGNAME" = "$line" && break
done
#done < "${1:-/dev/stdin}"

cmd="
gvfs-mount 'sftp://ndarmoni@xdev64.xcastlabs.com';
gvfs-mount 'sftp://ndarmoni@pbxdev.xcastlabs.com';
gvfs-mount 'sftp://ndarmoni@pps.siptalk.com';
mount_dev;
mount_pbxdev;
mount_usr
"
#echo "     $cmd"
#for line in $(echo $cmd | tr ";" "\n"); eval "'$line'"; done
eval "$cmd"
